const $=id=>document.getElementById(id);
const canvas=$('canvas'),ctx=canvas.getContext('2d'),KEY='one-card-templates-v1';
const fields=['bg','zoom','ix','iy','text','color','size','x','y','width','align'];
let image=null,imageData=null,selected=null,templates=[],renderTicket=0;
const ratios={'1:1':[1080,1080],'4:5':[1080,1350],'9:16':[1080,1920]};
function say(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error)}
function state(){let s={ratio:document.querySelector('[name=ratio]:checked').value,image:imageData};for(const id of fields)s[id]=['text','bg','color','align'].includes(id)?$(id).value:Number($(id).value);return s}
function wrap(text,font,width){ctx.font=font;let lines=[];for(const paragraph of text.split('\n')){let line='';for(const ch of Array.from(paragraph)){if(line&&ctx.measureText(line+ch).width>width){lines.push(line);line=ch}else line+=ch}lines.push(line)}return lines}
async function draw(){const ticket=++renderTicket;await document.fonts.ready;if(ticket!==renderTicket)return;const s=state(),[w,h]=ratios[s.ratio];canvas.width=w;canvas.height=h;ctx.fillStyle=s.bg;ctx.fillRect(0,0,w,h);if(image){let scale=Math.max(w/image.width,h/image.height)*s.zoom,dw=image.width*scale,dh=image.height*scale;ctx.drawImage(image,(w-dw)*s.ix/100,(h-dh)*s.iy/100,dw,dh)}
let px=Math.max(16,Math.min(160,s.size||16)),cx=w*s.x/100,cy=h*s.y/100;
let available=Math.min(w*s.width/100,2*Math.min(cx,w-cx)-32);available=Math.max(20,available);let maxHeight=Math.max(20,2*Math.min(cy,h-cy)-32),lines;
// Font fitting uses the same canvas coordinates for preview and export.
do{lines=wrap(s.text,`700 ${px}px system-ui, 'Malgun Gothic', 'Apple Color Emoji', 'Segoe UI Emoji', sans-serif`,available);if(lines.length*px*1.35<=maxHeight)break;px-=1}while(px>1);
ctx.font=`700 ${px}px system-ui, 'Malgun Gothic', 'Apple Color Emoji', 'Segoe UI Emoji', sans-serif`;ctx.fillStyle=s.color;ctx.textBaseline='top';ctx.textAlign=s.align;const tx=s.align==='left'?cx-available/2:s.align==='right'?cx+available/2:cx,ty=cy-lines.length*px*1.35/2;ctx.shadowColor='rgba(0,0,0,.22)';ctx.shadowBlur=px/12;for(let i=0;i<lines.length;i++)ctx.fillText(lines[i],tx,ty+i*px*1.35,available);ctx.shadowBlur=0;$('count').textContent=`${s.text.length} / 1500`;$('dimensions').textContent=`${w} × ${h} px`;canvas.style.aspectRatio=`${w}/${h}`}
function loadImage(data){return new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error('이미지를 읽을 수 없습니다. 기존 작업은 유지됩니다.'));i.src=data})}
function readData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('파일을 읽을 수 없습니다.'));r.readAsDataURL(file)})}
async function upload(file){if(!file)return;try{if(!['image/png','image/jpeg'].includes(file.type))throw new Error('PNG 또는 JPEG만 사용할 수 있습니다. 기존 작업은 유지됩니다.');if(file.size>8*1024*1024)throw new Error('이미지는 8MB 이하만 사용할 수 있습니다.');let i=await loadImage(await readData(file));if(i.width*i.height>20000000)throw new Error('이미지는 2천만 픽셀 이하만 사용할 수 있습니다.');const clean=document.createElement('canvas');clean.width=i.width;clean.height=i.height;clean.getContext('2d').drawImage(i,0,0);const data=clean.toDataURL('image/png');if(data.length>10000000)throw new Error('변환된 이미지가 너무 큽니다. 더 작은 이미지를 사용해 주세요.');let decoded=await loadImage(data);image=decoded;imageData=data;await draw();say('이미지를 불러왔습니다. 원본 메타데이터는 저장하지 않습니다.')}catch(e){say(e.message,true)}finally{$('imageFile').value=''}}
function download(data,name){const a=document.createElement('a');a.href=data;a.download=name;a.click()}
function jsonDownload(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));download(url,name);setTimeout(()=>URL.revokeObjectURL(url),1000)}
function validate(s){if(!s||typeof s!=='object'||Array.isArray(s))throw new Error('템플릿 설정이 올바르지 않습니다.');const ranges={zoom:[1,3],ix:[0,100],iy:[0,100],size:[16,160],x:[5,95],y:[5,95],width:[20,90]};for(const [k,[min,max]]of Object.entries(ranges))if(typeof s[k]!=='number'||!Number.isFinite(s[k])||s[k]<min||s[k]>max)throw new Error(`필수 항목 ${k}가 없거나 범위를 벗어났습니다.`);if(typeof s.text!=='string'||s.text.length>1500||!ratios[s.ratio]||!['left','center','right'].includes(s.align)||!/^#[0-9a-f]{6}$/i.test(s.bg)||!/^#[0-9a-f]{6}$/i.test(s.color))throw new Error('문구·화면비·색상 필수 항목을 확인해 주세요.');if(s.image!==null&&(typeof s.image!=='string'||!/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(s.image)||s.image.length>10000000))throw new Error('이미지 형식이 올바르지 않습니다.');return s}
function validateTemplate(t){if(!t||typeof t.id!=='string'||!t.id||typeof t.name!=='string'||!t.name.trim()||t.name.length>60)throw new Error('템플릿 이름 또는 ID가 올바르지 않습니다.');validate(t.settings);return {id:t.id,name:t.name,settings:t.settings}}
function persist(next){const value=JSON.stringify({version:1,templates:next});try{localStorage.setItem(KEY,value)}catch{throw new Error('브라우저 저장 공간이 부족하거나 저장이 차단되었습니다. 기존 템플릿은 유지됩니다.')}templates=next;renderTemplates()}
function renderTemplates(){const list=$('templateList');list.replaceChildren();$('updateTemplate').disabled=!templates.some(t=>t.id===selected);if(!templates.length){const p=document.createElement('p');p.className='hint';p.textContent='아직 저장한 템플릿이 없습니다.';list.append(p)}for(const t of templates){const item=document.createElement('div');item.className='template-item'+(selected===t.id?' selected':'');const load=document.createElement('button');load.className='template-load';const swatch=document.createElement('span');swatch.className='swatch';swatch.style.background=t.settings.bg;const label=document.createElement('span');label.textContent=t.name;load.append(swatch,label);load.onclick=async()=>{try{await apply(t.settings);selected=t.id;$('templateName').value=t.name;renderTemplates();say('템플릿을 불러왔습니다.')}catch(e){say(e.message,true)}};const del=document.createElement('button');del.className='template-delete';del.textContent='삭제';del.setAttribute('aria-label',`${t.name} 삭제`);del.onclick=()=>{if(!confirm(`“${t.name}” 템플릿을 삭제할까요?`))return;try{persist(templates.filter(v=>v.id!==t.id));if(selected===t.id)selected=null;renderTemplates();say('템플릿을 삭제했습니다.')}catch(e){say(e.message,true)}};item.append(load,del);list.append(item)}}
async function apply(s){validate(s);let nextImage=s.image?await loadImage(s.image):null;for(const id of fields)$(id).value=s[id];document.querySelector(`[name=ratio][value="${s.ratio}"]`).checked=true;image=nextImage;imageData=s.image;await draw()}
function save(update){try{let name=$('templateName').value.trim();if(!name)throw new Error('템플릿 이름을 입력해 주세요.');if(!update&&templates.length>=30)throw new Error('템플릿은 최대 30개까지 저장할 수 있습니다.');let id=update?selected:crypto.randomUUID();if(update&&!templates.some(t=>t.id===id))throw new Error('수정할 템플릿을 먼저 선택해 주세요.');const t={id,name,settings:state()};validateTemplate(t);persist(update?templates.map(v=>v.id===id?t:v):[...templates,t]);selected=id;renderTemplates();say(update?'템플릿을 수정했습니다.':'새 템플릿을 저장했습니다.')}catch(e){say(e.message,true)}}
async function importJson(file){if(!file)return;try{if(file.size>8*1024*1024)throw new Error('JSON 파일은 8MB 이하만 사용할 수 있습니다.');let data;try{data=JSON.parse(await file.text())}catch{throw new Error('JSON 문법이 손상되었습니다. 기존 템플릿은 유지됩니다.')}if(data.version!==1||!Array.isArray(data.templates)||!data.templates.length||data.templates.length>30)throw new Error('version 또는 templates 필수 항목이 올바르지 않습니다.');const incoming=data.templates.map(validateTemplate);if(new Set(incoming.map(t=>t.id)).size!==incoming.length)throw new Error('중복 ID가 있습니다.');for(const t of incoming)if(t.settings.image){const i=await loadImage(t.settings.image);if(i.width*i.height>20000000)throw new Error('복원 이미지가 너무 큽니다.')}const next=[...templates];for(const t of incoming){const index=next.findIndex(v=>v.id===t.id);if(index>=0)next[index]=t;else next.push(t)}if(next.length>30)throw new Error('복원 후 템플릿이 30개를 초과합니다.');persist(next);say(`템플릿 ${incoming.length}개를 복원했습니다.`)}catch(e){say(e.message+' 기존 템플릿은 유지됩니다.',true)}finally{$('jsonFile').value=''}}
for(const id of fields)$(id).addEventListener('input',draw);for(const r of document.querySelectorAll('[name=ratio]'))r.addEventListener('change',draw);
$('imageFile').onchange=e=>upload(e.target.files[0]);$('removeImage').onclick=()=>{image=null;imageData=null;draw();say('이미지를 지웠습니다.')};$('download').onclick=async()=>{await draw();canvas.toBlob(blob=>{if(!blob)return say('파일을 만들 수 없습니다.',true);const url=URL.createObjectURL(blob);download(url,`한장-${state().ratio.replace(':','x')}.png`);setTimeout(()=>URL.revokeObjectURL(url),1000);say('PNG 파일을 저장했습니다.')},'image/png')};$('saveTemplate').onclick=()=>save(false);$('updateTemplate').onclick=()=>save(true);$('exportJson').onclick=()=>{if(!templates.length)return say('먼저 템플릿을 저장해 주세요.',true);jsonDownload({version:1,templates},'한장-템플릿.json');say('템플릿을 JSON 파일로 내보냈습니다.')};$('jsonFile').onchange=e=>importJson(e.target.files[0]);
try{let raw=localStorage.getItem(KEY);if(raw){const data=JSON.parse(raw);if(data.version!==1||!Array.isArray(data.templates)||data.templates.length>30)throw new Error();templates=data.templates.map(validateTemplate)}}catch{say('저장한 템플릿을 읽을 수 없습니다. 기존 저장 데이터는 덮어쓰지 않았습니다.',true)}renderTemplates();draw();
// WebMCP mirrors the visible editor controls when the host browser supports it.
if(document.modelContext?.registerTool){const toolError=e=>say('도구 요청을 처리하지 못했습니다: '+e.message,true);void Promise.resolve(document.modelContext.registerTool({name:'stage_card_content',title:'카드 문구 설정',description:'편집기에 문구, 화면비, 배경색을 설정하고 미리보기를 갱신합니다.',inputSchema:{type:'object',properties:{text:{type:'string',maxLength:1500},ratio:{type:'string',enum:['1:1','4:5','9:16']},background:{type:'string',pattern:'^#[0-9a-fA-F]{6}$'}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){if(!input||typeof input.text!=='string'||input.text.length>1500)throw new Error('text가 필요하며 1500자 이하여야 합니다.');$('text').value=input.text;if(input.ratio){if(!ratios[input.ratio])throw new Error('지원하지 않는 화면비입니다.');document.querySelector(`[name=ratio][value="${input.ratio}"]`).checked=true}if(input.background){if(!/^#[0-9a-f]{6}$/i.test(input.background))throw new Error('배경색은 #RRGGBB 형식이어야 합니다.');$('bg').value=input.background}await draw();say('카드 문구를 설정했습니다.');return {status:'staged',ratio:state().ratio,textLength:input.text.length}}})).catch(toolError);void Promise.resolve(document.modelContext.registerTool({name:'read_card_state',title:'카드 상태 읽기',description:'현재 카드의 화면비와 문구 길이, 저장된 템플릿 수를 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(){return {ratio:state().ratio,textLength:$('text').value.length,templateCount:templates.length,hasImage:!!image}}})).catch(toolError)}
